### ISSUE TITLE
Añadir anuncios al servidor

### ISSUE THREAD

**Issue by faustinoco** [alejandrofortes/Practica-VVS#11]
No contempláis la posibilidad de coger los anuncios que estén en el servidor  a la hora de realizar la búsqueda..

**Comment by angelGarciaSantos** [comment]
No acabo de entenderlo. En la búsqueda revisamos todos los contenidos para ver si coinciden con lo que se está buscando, y cualquier contenido está almacenado en el servidor, en la lista "contenidos".

**Comment by faustinoco** [comment]
no es que lo tengáis mal , a lo mejor me exprese mal, sería una mejora a realizar porque en el enunciado no dice nada

**Comment by angelGarciaSantos** [comment]
Ok, pero, ¿en qué consistiría esta mejora exactamente? Es que no acabamos de entenderlo.

**Comment by jmrio** [comment]
La posibilidad de que crees una lista de publicidad en el servidor, de tal manera que cuando este devuelve una lista de canciones, pueda coger la publicidad que ya tiene el servidor registrado, en vez de estar creando un nuevo anuncio cada vez.

**Comment by angelGarciaSantos** [comment]
Ok ahora entiendo. Pero en este caso, como todos los anuncios son iguales (mismo nombre y duración) no veo la necesidad de almacenarlos en el servidor, simplemente incluirlos en la búsqueda en el momento que el usuario los pida. Si en algún momento los anuncios se diferencian entre sí, cambiaremos esta implementación.

**Comment by lauramcastro** [comment]
A alternativa a pechar esta issue, en caso de prever (se fose un proxecto real) que nalgunha iteración posterior ese requisito puidera realmente cambiar (que os anuncios deixen de ser iguais, algo moi plausible nunha filosofía áxil) sería deixala aberta como "enhancement".

**Comment by angelGarciaSantos** [comment]
Ok. Neste caso deixamola pechada.
