### ISSUE TITLE
Colaboración escasa.

### ISSUE THREAD

**Issue by lauramcastro** [alejandrofortes/Practica-VVS#2]
Un dos membros do equipo só incluiu o README no repositorio. Debedes mellorar o ratio de colaboración.

**Comment by angelGarciaSantos** [comment]
Alejandro foi o que subiu o esqueleto do proxecto, de modo que casi todos os ficheiros se subiron xuntos nese momento. Despois para implementar os métodos participamos ambos, como pode verse no historial de commits de GitHub.

**Comment by lauramcastro** [comment]
O problema (que se deu tamén en outros dous equipos alomenos) é que Ángel debe estar facendo os commits cun email que non é o que ten rexistrado en GitHub, e entón (podedes comprobar isto na lista de commits) non se asignan ao seu usuario @angelGarciaSantos e polo tanto el non aparece na lista de colaboradores. Deberiades poder arranxalo (non vai reescribir a historia, pero si para os commits que fagades a partir de ese momento).

**Comment by angelGarciaSantos** [comment]
Xa está solucionado.
