### ISSUE TITLE
Eliminacion de tests superfluos

### ISSUE THREAD

**Issue by vicfic** [alejandrofortes/Practica-VVS#7]
Deben de eliminarse tests que no ayudan en la validación del código. Ejemplo:

  public void testApp()
    {
        assertTrue( true );
    }

**Comment by angelGarciaSantos** [comment]
Hecho.

**Comment by lauramcastro** [comment]
Esta issue deberiades tela marcada como duplicado da #4 .

**Comment by angelGarciaSantos** [comment]
Correxido.
