### ISSUE TITLE
buscar cancion y buscar anuncio

### ISSUE THREAD

**Issue by vicfic** [alejandrofortes/Practica-VVS#9]
En las clases Anuncio y Cancion, se ha utilizado el metodo equals en el método buscar.

De esta manera no se permite buscar con subcadenas (deducido del diagrama UML del enunciado) 

Habría que hacer una implementación que permita buscar por subcadenas.

**Comment by alejandrofortes** [comment]
Error solucionado

**Comment by lauramcastro** [comment]
Esta issue, aínda que é o mesmo problema, ao materializarse en código de dúas clases diferentes, deberiamos tela reportada como dúas issues separadas (unha afectando a Canción e outra a Anuncio). Ao fin e ao cabo, tamén era o mesmo problema que o indicado na issue #10 que si foi informado separadamente.
